[[main]]
    name       = "首页"
    url        = "/"
    weight     = 10

    [main.params]
        icon = "home"

[[main]]
    name   = "归档"
    url    = "/archives/"
    weight = 20

    [main.params]
        icon = "archives"

[[main]]
    name   = "搜索"
    url    = "/search/"
    weight = 30

    [main.params]
        icon = "search"

[[main]]
    name   = "分类"
    url    = "/categories/"
    weight = 40

    [main.params]
        icon = "categories"

[[social]]
    identifier = "github"
    name       = "GitHub"
    url        = "https://github.com/wrightwei1118"

    [social.params]
        icon = "brand-github"

